---
#Degisken kullanarak playbook hazirlama  
  - hosts: all
    become: true
    tasks:
# Bu gorevler, Debian & Ubuntu tabanli sunucular icin    
    
    - name: Bu gorev Ubuntu & Rocky Linux Web Sunucu ve php kutuphanesi yuklemesini gerceklestirir.
      ansible.builtin.package:
        update_cache: yes
        name: 
          - "{{ apache_sunucusu }}"
          - "{{ php_kutuphane }}"
        state: latest  
      